services:
  pgdatabase:
    image: postgres:18
    container_name: pgdatabase
    environment:
      POSTGRES_USER: "thaivo"
      POSTGRES_PASSWORD: "02072007"
      POSTGRES_DB: "ny_taxi"
    volumes:
      - "ny_taxi_postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "quocthaibanana@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "02072007"
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8085:80"
    networks:
      - pg-network
    depends_on:
      - pgdatabase

networks:
  pg-network:
    driver: bridge

volumes:
  ny_taxi_postgres_data:
  pgadmin_data: